### ISSUE TITLE
typescript project, unable to resolve import

### ISSUE THREAD

**Issue by mjgoeke** [bakerstreet-industries/ts-log-class#4]
I'm trying to use this library.
after `yarn add ts-log-class`, in vscode I navigate to a .ts file with a class in it.

When I type `@log()` above my class, vscode suggests `import default 'log' from module "src/tslogclass"`.
It adds the line to the imports: `import log from 'src/tslogclass';`
This doesn't work. It looks like something's declared wrong in the package.json for this library.
I fix it up to say
`import log from 'ts-log'class';`
the error changes to `File '<project dir>/node_modules/ts-log-class/.webpack/@types/index.d.ts' is not a module`.

looks like another package.json problem.  I'll go fix it by hand. The `types` property looks to be incorrect, I change it from 
`"types": ".webpack/index.d.ts"` to
`"types": ".webpack/@types/index.d.ts"`
based on what I see in the filesystem.

vscode now complains `File '<project dir>/node_modules/ts-log-class/.webpack/@types/index.d.ts' is not a module`.
I look at the file and change the first line of index.d.ts from
`declare module "src/tslogclass" {` to
`declare module "ts-log-class" {`

It now seems to work.  It looks like something didn't get configured correctly during this library's webpack build for external consumers of the package.

**Comment by Roustalski** [comment]
Thanks for letting us know. We will take a look

**Comment by Roustalski** [comment]
Thanks for bringing this to our attention. It is fixed and published to NPM version `1.1.2` Thank you!
